# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d84a8c6a0e09ad9ad51dbc9630d4ea28ae3fcf967f9a82ef97626fcbc8adcb024a546bd4c07445cc2d0319699d910a330074c05c91dcc6a9a05deb04d70d7d1

test:
  secret_key_base: 0c37895f0e4a547f9200eb6f671f3c5ab1e90a85abe83b55b42c4f849e2be86ac25a43ae5607a9955cec0bc98074d551666cf8e166097a5621f3a73a53c12239

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 0c37895f0e4a547f9200eb6f671f3c5ab1e90a85abe83b55b42c4f849e2be86ac25a43ae5607a9955cec0bc98074d551666cf8e166097a5621f3a73a53c12239
